### ISSUE TITLE
[Question] Is it suitable for my use case

### ISSUE THREAD

**Issue by ricky11** [Touffy/client-zip#12] opened 2021-01-31 07:07 UTC
My users upload multiple files for retrieval later using S3.

*Up to 100 files (max 500) can be uploaded at one time
*Total Size average's from 200mb up to 6GB or more.
*Current use case is that when the clients want to download it they have the option to download individually, or i force the browser to download multiple files!  

I have been looking for a way to either compress the files from s3 along with the key stream, zip and download.
OR create the zip client side and then upload.
I dont need to compress.

I wonder if client-zip would be suitable, the only current limitation would be the 4gb limit, but then i may be able to separate the zips.

Thanks
Ricky

**Comment by Touffy** [comment] 2021-01-31 09:27
Hi. As you say, the 4GB limitation would be a hard issue for some users (an issue that I do plan to fix in client-zip by implementing ZIP64). Then there is a soft issue with large archives…

The file count is not a problem at all. There is no inherent limitation or performance bottleneck there. Just make sure to fetch the files lazily in sequence with an async generator, do not use `Promise.all` or something like that. You can pass an async generator to `downloadZip` instead of an array.

In fact, downloading lots of small files with a low total size is a better use case for client-zip than a few really large ones. If you use the simple Blob method to create a download link, the browser needs to generate and cache the whole ZIP rather than stream it to the disk as it is being generated. That's barely noticeable below 100MB, but the browser will probably complain to the user about high CPU and memory usage from a page that generates a 4GB blob (and you must show the user a progress bar to make the wait acceptable).

The solution to the long-ish processing time and large memory usage, of course, is to stream the response straight to the disk, as it is generated, without calling `.blob()`. There are two ways of doing that:

* The easy way is by using a currently non-standard Filesystem API in write mode, that is only supported in Chrome, which allows you to programmatically write to a file without clicking a download link. You would simply pipe the Response's body into the File. Solved in one line ! (plus the creation of the file and asking for permission, but still trivial). But if you have that API, you could skip the zipping entirely and just write all the files one by one.
* The way that *should* work everywhere is by using a ServiceWorker to intercept the page's request from a vanilla link (not a Blob URL) and stream the response. I have run into some trouble in my attempt to document how to do just that, so at the moment I can say it's theoretically possible but ServiceWorkers and `download` links don't mix well.

**Comment by Touffy** [comment] 2021-02-10 10:09
**Update**: The problem with download links and ServiceWorkers was limited to Safari (sadly, it's been a known bug for a long time and still not fixed). I will soon publish the results.

**Comment by ricky11** [comment] 2021-02-10 16:57
Thanks, will give it a shot, your answer was extremely details, parts of it went over my head.

How does jszip work with large zips over 4gb.. 

Is this how sites like dropbox and we transfer handle it, zip client side and then download?

My use case is all sizes of fies up to 5gb per file. (i dont need compression) just a large 1 file archive.

will do some testing...

when would you be able to support zip64, what are the hurdles invovled?

rishi

**Comment by Touffy** [comment] 2021-02-10 17:44
> How does jszip work with large zips over 4gb..

Today it doesn't (actually, there is no error catching code for that case, so it will generate a corrupted archive). The original ZIP file format simply does not understand archives larger than 4GB. An extension to the format called ZIP64 was later added to allow larger files, but implementing ZIP64 is… let's say *annoying* until BigInt64Arrays and writing BigInt64 with DataViews are well supported in browsers. That is why I don't support it yet.

Ideally, if you have efficient access to file metadata, you should use that knowledge to prevent the creation of the ZIP file before even calling `downloadZip`. My library itself is designed to consume the files one by one, without looking ahead, so it cannot detect in advance that the total size will exceed 4GB.

> Is this how sites like dropbox and we transfer handle it, zip client side and then download?

I seriously don't think so. I assume that they generate the ZIP server-side (possibly on an edge server). It's faster than doing it client-side if you can afford the high-speed network backbone and CPU.

> when would you be able to support zip64, what are the hurdles invovled?

The "when" depends on demand (it's doable today, just not as straightforward as it could be), and on browser support for the features that would make it straightforward. And, well, on my own energy. It's not a huge feature in terms of code. If I were highly motivated, I guess I could finish it in a few weeks. But if I wait for browser support, maybe a year.

As for you, it won't change a thing in the API of client-zip (maybe I'll add an option to force the old format, but ZIP64 will be the default). So, let's say you implement your solution with client-zip today, with some UI workaround to prevent >4GB downloads (at that point, I guess it's not such a big deal if you have to download each file separately, but maybe it is). Then, when ZIP64 is supported, you just upgrade client-zip to the new version, remove the UI limitation, and your solution will immediately work with any file size (up to 18 Zettabytes 😀). Just **make sure you use streaming** because creating large ZIP files without streaming will really hurt your app's usability and also just crash the app when it runs out of RAM.

**Comment by Touffy** [comment] 2021-02-11 12:40
I've delved a little deeper into the 64-bit issues, and it's actually not that hard to polyfill the couple of ArrayBuffer features I need. It's not going to work without BigInts, though. So browsers from 2019 won't be supported.

**Comment by Touffy** [comment] 2021-02-11 19:23
Alright, it was easier than I thought. It's still a bit rough around the edges, but I think I got Zip64 working. I've published a PR and version 2.0.0-rc1 on npm. Please give it a try with large files and tell me if it works.

**Comment by Touffy** [comment] 2021-02-20 17:55
Turns out the rc1 was not generating correct Zip64 archives, but I've done some real testing for the rc2 I just published and I hope you can confirm it is finally working as intended. I'd like to have your feedback before I publish the definitive v2.0.0.

**Closed** 2021-03-16 09:38 UTC
Labels: question
