### ISSUE TITLE
[BUG] zero-length files

### ISSUE THREAD

**Issue by demidov71** [Touffy/client-zip#38] opened 2022-05-07 14:55 UTC
"predictLength" fails to predict anything with zero length - file, string, array etc. It complains, that size is missing for that item.
On the other hand, "downloadZip" has no problem with those items.

**Comment by Touffy** [comment] 2022-05-07 15:02
I see how that would happen. Easy to fix. Though, if I may ask — if you know the files are empty, why store them at all ?

**Comment by demidov71** [comment] 2022-05-07 15:11
Those are not my files, but my customers'. They have their reasons.
My product filters their files, so it should handle zero-length ones as well.

By the way, very fast performance! I use it to stream-upload multiple huge files on a single connection and get progress.

**Comment by Touffy** [comment] 2022-05-07 15:47
Alright. It should be fixed in the newly published version 2.2.1.

Good to hear that client-zip otherwise works as intended.

**Closed by Touffy** 2022-05-07 15:47 UTC
Labels: bug

**Comment by demidov71** [comment] 2022-05-08 01:21
Thank you. Now works with zero-length files as expected .
